### ISSUE TITLE
Simperium is having a hard time syncing a large amount of objects from a bucket.

### ISSUE THREAD

**Issue by lukegeiger** [Simperium/simperium-ios#485] opened 2015-05-20 17:45 UTC
Hi @jleandroperez. After logging onto a certain account in my app that has maybe around ~110k instances stored in a bucket, simperium has a hard time bringing all of those back down into Core Data. What happens is Simperium prints out a never ending cycle of 

    2015-05-20 13:43:13.816 HM[3573:981409] Simperium processing 10214 objects from index (Log)
    2015-05-20 13:43:15.753 HM[3573:981411] Simperium enqueuing 10212 object requests (Log)

This gets printed out every few seconds or so, but no Log Instances every actually end up in Core Data. I know this because If I stop the app and re run I see 

    2015-05-20 13:43:08.647 HM[3573:981385] Simperium managing 0 Log object instances

I have verbose logs for this if you need it.

**Comment by jleandroperez** [comment] 2015-05-21 13:01
Hello there @lukegeiger!

Sure, i'll take a look. Can you please send the log files over to `jorge [at] automattic (dot) com` ?
Have you been able to reproduce this with any other account?. I've tried out [with this sample app](https://github.com/jleandroperez/simperium-debug-ios), but couldn't spot anything odd.

Thanks!

**Comment by lukegeiger** [comment] 2015-05-21 19:38
@jleandroperez Ok I just sent over the logs. Yes I have been able to reproduce. If need be, I can get you access to one of the accounts having issues on my app.

**Comment by jleandroperez** [comment] 2015-05-22 13:05
@lukegeiger ahhhhhhh my bad. I was wondering why i wasn't seeing the logs... `jorge.perez [at] automattic (dot) com` would be the right one. Would it be possible to please resend it?

I'm very sorry... i swear it happens when you've got many accounts!.

Thanks!

**Comment by lukegeiger** [comment] 2015-05-23 18:22
@jleandroperez No problem, just sent them again!

**Comment by jleandroperez** [comment] 2015-05-26 16:44
@lukegeiger thank you sir!. Few highlights:

- The client successfully gets the `Log` bucket's index, and requests 10212 entities:
  `Simperium enqueuing 10212 object requests (Log)`
- Effectively, 10212 entities get requested:
  `Simperium downloading entity (Log)`
- Apparently, only the first (two) entities get downloaded:
  `c0e4e41390554ec6b36d8ef7d8022278` + `ddd31181bea24d05b55ea24cce881769`

Would it be possible to [change this log](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/SPWebSocketChannel.m#L438) call to `SPLogInfo` instead? (i've just pushed that change into Develop).

Also, please, perform the exact same change [in this spot](https://github.com/Simperium/simperium-ios/blob/develop/Simperium/SPWebSocketInterface.m#L381), and try performing a fresh install + sync'ing.

Once ready, would it be possible to get the updated logs?.

Thanks in advance Luke!

**Comment by lukegeiger** [comment] 2015-05-28 19:09
Hey @jleandroperez sorry for late response on this, the notifications stopped coming to my phone for some reason... Yeah for sure, just sent you the updated logs. In this case, it seems like no Log instances are getting downloaded.

**Comment by jleandroperez** [comment] 2015-05-29 20:14
@lukegeiger again, thanks for the logs!. Not sure what might be going on, only few entities appear to be downloaded.

I've just replied you via email, would it be possible to test this on my end?.
Thanks!

**Comment by lukegeiger** [comment] 2015-05-29 20:19
@jleandroperez yeah for sure. I added you to my repo, and replied to your email with steps to reproduce.

**Comment by jleandroperez** [comment] 2015-05-29 20:58
@lukegeiger thank you sir!.

I'm afraid i just tested (iPhone 6 Simulator, Xcode 6.3.2), and precisely 10214 Log Entities got downloaded.

I'm sending you, via mail, my logs. I hacked two spots of **SPWebSocket**, so that it prints out I/O synchronously (methods **send:** and **webSocket:didReceiveMessage:**).

Not sure what might be the difference, i'll retry on the actual device, but given the fact that few entities get downloaded on your end... (maybe?) networking issues?.

**Comment by jleandroperez** [comment] 2015-05-29 21:33
@lukegeiger allright! reproduced on an iPad Mini (iOS 8.3).

I'll be working on this one next week. Not quite sure why it's only happening in the device, but nevertheles, glad we could catch it.

Will keep you posted Luke!

**Comment by lukegeiger** [comment] 2015-05-29 21:34
@jleandroperez Yeah sorry I forgot to mention you have to use it on a device to reproduce. Ok cool, just ping me if you need me. Have a nice weekend!

**Comment by jleandroperez** [comment] 2015-05-29 21:35
No worries Luke!. Thanks for helping us out, have an awesome weekend!

**Comment by lukegeiger** [comment] 2015-06-03 04:25
Hey @jleandroperez have you gotten a chance to take a look at this yet?

**Comment by jleandroperez** [comment] 2015-06-03 19:32
@lukegeiger i'm sorry about the delay here. I've managed to confirm the bug on friday, and *just* managed to reproduce the exact same behavior on a standalone app.

I'll be working on a fix this week, from what i can tell, this could be caused by an excesive number of requests over the websocket channel. Will keep you posted!

**Comment by jleandroperez** [comment] 2015-06-04 20:44
@lukegeiger should be fixed in PR #487, would it be possible to validate the fix?.

Branch `issue/485-paging-entity-requests` (looking good on my side).

Thank you!

**Comment by lukegeiger** [comment] 2015-06-05 21:58
@jleandroperez Yes, I can confirm! Nice work man!

**Comment by jleandroperez** [comment] 2015-06-05 22:46
Awesome, thanks for reporting this issue @lukegeiger!!

If anything, please, just let us know!

**Closed by jleandroperez** 2015-06-05 22:46 UTC
Labels: bug
