### ISSUE TITLE
Simperium not remembering state on logging in on simulator

### ISSUE THREAD

**Issue by lukegeiger** [Simperium/simperium-ios#561] opened 2016-12-07 16:20 UTC
Steps to reproduce.

1. Log in or sign up
2. Auth screen dismisses.
3. kill app.
4. Re Launch
5. You are asked to log in again with the error Simperium did not find user in keychain.

*Note, I am not using SPAuthenticaionViewController I am just using a plain UIViewController that subscribes to SPAuthenticatorDelegate

Please let me know what logs/more information you need.

**Comment by jleandroperez** [comment] 2016-12-07 19:48
Hey there @lukegeiger,

Can't reproduce on my end. Sounds likea  potential keychain glitch. 

- Would it be possible to get the snippets you're using to authenticate your app?. 
- Are you getting any error logs in the console?
- Did this happen on the simulator or the actual device? have you tried a fresh install?
- Is this something you can repro 10 out of 10?

Thanks!

**Comment by jleandroperez** [comment] 2019-12-20 11:57
Closing this one, still cannot repro. Hope everything is great over there Luke!

**Closed by jleandroperez** 2019-12-20 11:57 UTC
